config/routes.rb
Rails.application.routes.draw do
  
  
  post 'status_ts_ol/create_comment_ol'
  get 'status_ts_ol/index'
  delete 'status_ts_ol/index'

  get 'status_ts/index'
  delete 'status_ts/index'
  get 'status_ts/show_filter_and_search'

  get 'proposal/cancels'
  post 'proposal/cancels'
  delete 'proposal/cancels'
  get 'proposal/works_dt'
  get 'proposal/works'
  get 'proposal/set_work'
  get 'proposal/job_requests'
  post 'proposal/set_work'
  delete 'proposal/set_work'
  get 'proposal/work_locations'
  get 'proposal/index'
  get 'proposal/show_entry_cancels'
  get 'proposal/show_work_cancels'
  get 'proposal/entries'
  get 'proposal/add_city_to_entry'
  get 'proposal/set_entry'
  post 'proposal/set_entry'
  delete 'proposal/set_entry'
  get 'proposal/set_reason'
  get 'proposal/add_cancel_to_reason'
  post 'proposal/set_reason'
  delete 'proposal/set_reason'
  get 'proposal/set_deps_reason'
  post 'proposal/set_deps_reason'
  delete 'proposal/set_deps_reason'

  get 'tariff_calculator/all_tariffs'
  post 'tariff_calculator/all_tariffs'
  get 'tariff_calculator/get_cities'
  get 'tariff_calculator/market'
  post 'tariff_calculator/market_get_tariff_grid'
  get 'tariff_calculator/edit_current_market_tariff'
  post 'tariff_calculator/save_current_market_tariff'
  delete 'tariff_calculator/destroy_current_market_tariff'
  get 'tariff_calculator/average'
  get 'tariff_calculator/average_active_regions'
  get 'tariff_calculator/average_active_cities'
  get 'tariff_calculator/set_seasons'
  post 'tariff_calculator/set_seasons'
  get 'tariff_calculator/zero'

  get 'truck_responsibles/index'
  get 'truck_responsibles/show_responsibles'
  get 'truck_responsibles/delete_responsible'
  get 'truck_responsibles/new_or_edit'
  post 'truck_responsibles/create_or_update'

  resources :modulators, except: [:show] do
    collection do
      post 'set_date'
    end
  end

  resources :extra_spendings do
    collection do
      get 'get_truck_and_payments'
      get 'payments'
      post 'payments'
      post 'set_date'
      get 'set_date'
    end
  end

  resources :extra_spending_types, except: [:show]

  resources :time_zones

  get 'reports/ts_spb'
  get 'reports/operation_log'

  post 'save_reports_xls/index'

  resources :gps_nav_transports do
    member do
      get 'show_gps_nav'
      get 'unchain_gps_nav'
    end
  end

  resources :transportmodel1cs

  resources :resource_characteristic_values

  resources :vacations do
    collection do
      get 'index'
      get 'get_form'
      post 'index'
    end
  end

  resources :booking_histories

  resources :contacts, except: [:show]

  resources :contact_types, except: [:show]

  resources :bookings do
    collection do
      get 'get_bookings'
      get 'transport_planning'
      get 'open_orders'
      get 'planned'
      get 'characteristic_val'
      get 'save_param'
      delete 'save_param'
      get 'show_filter_and_search'
      get 'select_filter'
      get 'save_xls'
      get 'select_truck'
      get 'empty_mileage'
      get 'get_city_locations'
      post 'save_empty_mileage'
      post 'save_truck'
      get 'get_column_values'
    end  
  end

  resources :booking_types

  resources :contractor_responsibles, except: [:show] do
    member do
      get 'show_responsibles'
      get 'unchain_responsible'
    end
  end

  resources :properties

  resources :monitoring_connections, only: [:index] do
    collection do
      get 'save_param'      
      delete 'save_param'
      get 'select_filter'
      post 'index'
      post 'create_comment'
      post 'agree'
      post 'quick_agree'
      delete 'quick_disagree'      
      delete 'disagree'
    end
  end

  
  get 'monitoring_resource_unavailable/index', as: :monitoring_resource_unavailable
  post 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/save_xls'

  get 'monitoring_fuel_stations/index', as: :monitoring_fuel_stations
  post 'monitoring_fuel_stations/index'
  get 'monitoring_fuel_stations/save_xls'
  post 'monitoring_fuel_stations/save_reports_xls'
  post 'monitoring_fuel_stations/refuellings'
  get 'monitoring_fuel_stations/info_by_azs_name'
  get 'monitoring_fuel_stations/expensive_refuellings'
  post 'monitoring_fuel_stations/expensive_refuellings'

  get 'uploadings/index'
  post 'uploadings/index'
  get 'uploadings/save_param'
  get 'uploadings/show_filter_and_search'

  resources :stream, only: [:uploading]

  get 'contractor_reports/save_xls'
  get 'contractor_reports/report_info'
  get 'contractor_reports/report'
  get 'contractor_reports/index'
  post 'contractor_reports/show'

  resources :contractor_analysis_parameter_changes

  resources :contractor_analysis_parameters

  resources :truck_comments

  get 'api/prm_questions'
  get 'api/show_question'
  get 'api/show_prm_question'
  post 'api/reply_prm'
  get 'api/reply'
  post 'api/send_answer'
  post 'api/send_open_answer'
  post 'api/get_azs'
  post 'api/set_azs'

  get 'payslips/index'
  post 'payslips/show'

  resources :question_answers

  resources :agreement_requests do
    collection do
      post 'index'
      get 'index'
    end
  end

  resources :agreement_accesses, except: [:show]

  resources :agreements, except: [:show]

  resources :process_statuses

  resources :task_statuses

  resources :task_action_accesses

  resources :process_action_accesses

  resources :template_steps

  resources :process_actions

  resources :task_actions

  resources :process_templates

  resources :process_types

  resources :citizenships

  resources :task_templates

  resources :task_types

  resources :contract_relationships

  resources :contracts

  resources :contract_kind_roles

  resources :contract_subkinds

  resources :contract_kinds

  resources :contract_types

  resources :contractor_representatives

  resources :unv_comments

  resources :truck_drivers, except: [:show] do
    collection do
      post 'index'
    end
  end

  resources :couplers do
    member do
      get 'unchain'
    end
  end

  resources :unv_employees

  resources :resourse_types

  resources :unv_types

  resources :employee_histories

  resources :employees
  post "employees/index"

  resources :staff_units

  resources :departments do

  end

  get "unavailables/index" => "unavailables#index"
  get "unavailables/ol" => "unavailables#ol"
  get "unavailables/connections" => "unavailables#connections"
  post "unavailables/index" => "unavailables#index"
  post "unavailables/ol" => "unavailables#ol"
  post "unavailables/connections" => "unavailables#connections"
  post "unavailables/save_xls" => "unavailables#save_xls"
  post "unavailables/show_filter_and_search" => "unavailables#show_filter_and_search"
  post "unavailables/create_comment" => "unavailables#create_comment"
  post "unavailables/create_comment_ol" => "unavailables#create_comment_ol"
  post "unavailables/agree" => "unavailables#agree"
  post "unavailables/quick_agree" => "unavailables#quick_agree"
  delete "unavailables/disagree" => "unavailables#disagree"

  resources :duties do
    collection do
      get 'add_all'
    end  
  end

  resources :tables

  resources :columns

  resources :objecttypepropertycolumns

  resources :objecttypeproperties

  resources :objecttypes

  resources :systems

  resources :phoneuses

  resources :phones

  resources :positions

  resources :contractortypes

  resources :contractors

  resources :documents do
    collection do
      get 'show_part'
      post 'select_kind'
      post "new_from"
      get 'select_kind'
      get 'edit'
      delete 'del_file'
    end
  end
  post "documents/select_transport/:id" => 'documents#select_transport'

  resources :documentkinds

  resources :documenttypes

  resources :functionalgroups do
    collection do
      post 'savesort'
      get 'savesort'
      get 'update_menu'
    end
  end

  resources :people do
    collection do
      post 'phone_person'
      get 'new_person'
      get 'phone_person'
      get 'drivers'
    end
  end

  resources :transportexploitations

  resources :transporttanks

  resources :transportloadings

  resources :transportecologicals

  resources :enginemodels

  resources :enginetypes

  resources :transportkinds

  resources :transportcolors

  resources :transporttypes

  resources :transports do
    collection do
      get 'groupings'
      post 'create_and_update_coupler'
      patch 'create_and_update_coupler'
      post 'create_and_update_driver'
      patch 'create_and_update_driver'
      get 'get_transportkind'
    end
    member do
      get 'show_couplers_and_drivers'
      get 'show_couplers'
      get 'show_drivers'
      get 'new_and_edit_coupler'
      get 'unchain_coupler'
      get 'new_and_edit_driver'
      get 'unchain_driver'
    end
  end
  post "transports/select_brand/:id" => "transports#select_brand"
  post "transports/select_tank/:id" => "transports#select_tank"
  post "transports/select_color/:id" => "transports#select_color"
  post "transports/select_enginemodel/:id" => "transports#select_enginemodel"
  post "transports/select_exploitation/:id" => "transports#select_exploitation"

  get "sms/index"
  post "sms/send_sms"

  resources :testguids, as: 'tst'

  resources :temps do
    collection do
      get 'strm'
    end

  end

  resources :roles
  post "roles/select_functional/:id" => "roles#select_functional"

  get "main/index"

  root :to => 'main#index'
  get '/' => 'main#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  post 'users/select_role/:id' => "users#select_role"
  post 'users/select_f_group/:id' => "users#select_f_group"

  scope "/admin" do
    resources :users, :usergroups, :roles, :functionals
  end

app/models/transport.rb
class Transport < ActiveRecord::Base

  before_validation :ensure_uuid
  validates :reg_num, presence: true
  validates :year,  presence: true,
                    numericality: true,
                    length: {minimum: 4, maximum: 4},
                    allow_blank: true 
  validates :reg_num, uniqueness: true #, on: :update
  validates :vin, uniqueness: true, allow_blank: true 

  has_and_belongs_to_many :gps_navs, through: :gps_nav_transports
  has_and_belongs_to_many :enginemodels
  has_and_belongs_to_many :documents
  
  has_many :tsloadings
  has_many :tstanks

  
  belongs_to :transportexploitation
  belongs_to :transportcolor
  belongs_to :transportmodel
  belongs_to :contractor
  
  has_many :coupler_trucks, -> { visible }, :class_name => 'Coupler', :foreign_key => 'truck_id'
  has_many :coupler_trailers, -> { visible }, :class_name => 'Coupler', :foreign_key => 'trailer_id'
  has_many :chained_coupler_trucks, -> { chained }, :class_name => 'Coupler', :foreign_key => 'truck_id'
  has_many :chained_coupler_trailers, -> { chained }, :class_name => 'Coupler', :foreign_key => 'trailer_id'

  has_many :truck_drivers, -> { visible }
  has_many :chained_truck_drivers, -> { chained }, :class_name => 'TruckDriver'

  has_many :gps_nav_transports, -> { visible }
  has_many :chained_gps_nav_transports, -> { chained }, :class_name => 'GpsNavTransport'
  

  default_scope lambda { order(:reg_num) }  
  scope :visible, lambda { where("transports.is_close != ?", true) }
  scope :trucks, lambda {visible.joins(transportmodel: [ transportkind: :transporttype ] ).where("[transporttypes].id = ?", 'eee53245-a100-42d3-8b36-c4b891dca119').order(:reg_num)}
  scope :trailers, lambda {visible.joins(transportmodel: [ transportkind: :transporttype ])
            .where("[transporttypes].id = ? or [transporttypes].id = ? or [transporttypes].id = ? or [transporttypes].id = ? ",
              '1e475762-b77b-427b-99de-e9350b455b13' , 'f8902d5a-762b-4188-b698-b893fbc0553c', '1d7b592f-8d12-4c4d-bc5a-71484efc1fff', '2c505e83-7074-46b1-ad55-5254a7067476').order(:reg_num)}
          
  scope :used_trucks, lambda { visible.joins(:coupler_trucks).where("couplers.end_date > ? or couplers.end_date IS NULL", Time.now) }
  scope :used_trailers, lambda { visible.joins(:coupler_trailers).where("couplers.end_date > ? or couplers.end_date IS NULL", Time.now) }
  scope :free_trucks, lambda { trucks.includes(:chained_coupler_trucks, :chained_truck_drivers) - used_trucks }
  scope :free_trailers, lambda { trailers.includes(:chained_truck_drivers) - used_trailers.includes(:chained_truck_drivers) }
  scope :without_driver, lambda { trucks.includes(:chained_coupler_trucks, :chained_truck_drivers) - trucks.joins(:chained_truck_drivers) }
  scope :without_gps, lambda { trucks.includes(chained_gps_nav_transports: [:gps_nav, :user]) - trucks.joins(chained_gps_nav_transports: [:gps_nav, :user]) }
#  scope :without_driver, lambda { trucks.joins('LEFT OUTER JOIN truck_drivers ON truck_drivers.transport_id = transports.id').where("(truck_drivers.transport_id IS NULL) OR (NOT(truck_drivers.end_date IS NULL) OR (truck_drivers.end_date < ?))", Time.now) }
#  scope :without_driver, lambda { (trucks.includes(:truck_drivers).where(truck_drivers: { id: nil })).joins(:truck_drivers).where("truck_drivers.end_date < ?", Time.now) }
  #scope :without_driver, lambda { trucks.includes(:truck_drivers).where("(truck_drivers.transport_id IS NULL) OR truck_drivers.end_date < ?", Time.now) }

  
  def truck?
    transportmodel.transportkind_id == '27f61ba9-8d2d-489c-b890-f16423b4b935' if transportmodel
  end

  def trailer?
    !truck?
  end
  
  # --------------------------------------------------------------------------------------------
  def coupler_trailer_num
    chained_coupler_trucks.any? ? chained_coupler_trucks.map { |c| c.trailer_num }.compact.join(', ') : ""
  end  
  
  def coupler_start_date
    chained_coupler_trucks.any? ? chained_coupler_trucks.pluck(:start_date).compact.join(', ') : ""
  end
  
  def coupler_end_date
    chained_coupler_trucks.any? ? chained_coupler_trucks.pluck(:end_date).compact.join(', ') : ""
  end

  def driver_name
    chained_truck_drivers.any? ? chained_truck_drivers.map { |d| d.person_info }.compact.join(', ') : ""
  end

  def driver_start_date
    chained_truck_drivers.any? ? chained_truck_drivers.pluck(:start_date).compact.join(', ') : ""
  end

  def driver_end_date
    chained_truck_drivers.any? ? chained_truck_drivers.pluck(:end_date).compact.join(', ') : ""
  end
  # --------------------------------------------------------------------------------------------

  def gps_nav_name
    chained_gps_nav_transports.any? ? chained_gps_nav_transports.map { |g| g.gps_nav.name if g.gps_nav }.compact.join(', ') : ""
  end

  def gps_start_date
    chained_gps_nav_transports.any? ? chained_gps_nav_transports.pluck(:start_date).compact.join(', ') : ""
  end

  def gps_end_date
    chained_gps_nav_transports.any? ? chained_gps_nav_transports.pluck(:end_date).compact.join(', ') : ""
  end
  
  def editor_name
    chained_gps_nav_transports.any? ? chained_gps_nav_transports.map { |g| g.user.fullname if g.user }.compact.join(', ') : ""
  end
  # --------------------------------------------------------------------------------------------

  def inside_contractor?
    contractor.inside? if contractor
  end
  
  def document
    documents.any? ? documents.first : false
  end

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end

  def transporttype
    self.transportmodel && self.transportmodel.transportkinds.first.any?  && self.transportmodel.transportkinds.first.transporttype ? self.transportmodel.transportkinds.first.transporttype : false
  end


  def enginemodel
    enginemodels.any? ? enginemodels.first : false
  end


 private 

 def ensure_uuid
    self.id ||= SecureRandom.uuid
 end


end

app/models/transporttype.rb
# -*- encoding : utf-8 -*-
class Transporttype < ActiveRecord::Base
#  attr_accessible :name, :transportcategory_id , :descr, :is_close

  #audited

  belongs_to :transportcategory
  has_many :transportkinds

  validates :name, presence: true

  scope :visible, lambda {where("is_close != ?", true)}

  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end


end

app/helpers/transports_helper.rb
module TransportsHelper
  
  def can_edit_locked_coupler?(coupler)
    !coupler.locked_to_date? || (coupler.locked_to_date? && user_can_edit_locked_coupler?(coupler))
  end
  
  def user_can_edit_locked_coupler?(coupler)
    current_user.admin || current_user.roles.pluck(:name).include?('Блокировка сцепок')
  end
  
  
end

app/views/transports/_docs.erb
<table>
  <tr>
    <th> Документы:</th><td colspan="2"><%= link_to "Создать документ", action: "show_part", part: "select_new_document", id: @transport,  remote: true %> </td>
  </tr>
  <% @transport.documents.visible.each do |document| %>
  <tr>
    <th><%=  document.documentkind.name if document.documentkind %></th> 
    <td class="edit" title="Редактировать"><%= link_to image_tag("edit.png"),edit_document_path(document) %></td>
    <td class="del" title="Удалить"><%= link_to image_tag("remove.png"), action: :remove_doc, id: document, method: :delete, data: { confirm: 'Точно?' } %></td>
  </tr>
   <% end if @transport.documents.any? %>
</table>

app/views/transports/_new_and_edit_coupler.html.haml
= form_for @coupler, url: create_and_update_coupler_transports_path, html: { class: "well well-sm", role: "form" }, remote: true do |f|
  -if  @coupler.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "Ошибок: #{@coupler.errors.count} "
      %ul
        - @coupler.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :id unless @coupler.new_record?
  = f.hidden_field :truck_id
  .alert.alert-info
    %strong Тягач
    = @truck.reg_num

  .form-group.input-group
    %span.input-group-addon
      %i Прицеп:
    - if @coupler.new_record?
      = f.collection_select( :trailer_id, @coupler.id.nil? ? @free_trailers : (@free_trailers << @coupler.trailer), :id, :reg_num, |
            { prompt: @coupler.trailer_id ? nil : "Выберите прицеп", |
            selected: @coupler.trailer_id ? @coupler.trailer_id : nil  }, class: "form-control" )
    - else
      = text_field_tag :trailer, @coupler.trailer_num, disabled: 'disabled', class: "form-control"

  .form-group.input-group
    %span.input-group-addon
      %i Начало взаимодействия:
    = f.text_field :start_date, class: "form-control"
    %span.input-group-addon
      %i Окончание взаимодействия:
    = f.text_field :end_date, class: "form-control"

  - if user_can_edit_locked_coupler?(@coupler)
    .form-group.input-group
      %span.input-group-addon
        %i Заблокировано до:
      = f.text_field :locked_to_date, class: "form-control"
      %span.input-group-addon
        %i.glyphicon.glyphicon-remove.red{:title => "Сбросить блокировку", :style => "cursor: pointer"}

  = f.submit 'Сохранить', class: 'btn btn-primary btn-sm'


:coffeescript
  $('#coupler_start_date').datetimepicker timepicker: true
  $('#coupler_end_date').datetimepicker timepicker: true
  $('#coupler_locked_to_date').datetimepicker timepicker: true
  $('#popup_content .glyphicon-remove').click ->
    $('#coupler_locked_to_date').val ''

app/views/transports/_new_and_edit_driver.html.haml
= form_for @truck_driver, url: create_and_update_driver_transports_path, html: { class: "well well-sm", role: "form" }, remote: true do |f|
  -if  @truck_driver.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "Ошибок: #{@truck_driver.errors.count} "
      %ul
        - @truck_driver.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :id unless @truck_driver.new_record?
  = f.hidden_field :transport_id
  .alert.alert-info
    %strong Тягач
    = @truck.reg_num

  .form-group.input-group
    %span.input-group-addon
      %i Водитель:
    - if @truck_driver.new_record?
      = f.collection_select( :employee_id, @free_drivers , :id, :person_info, |
        { prompt: @truck_driver.employee_id ? nil : "Выберите водителя", selected: @truck_driver.employee_id ? @truck_driver.employee_id : nil  }, class: "form-control" )
    - else
      = text_field_tag :driver, @truck_driver.employee.person_info, disabled: 'disabled', class: "form-control"

  .form-group.input-group
    %span.input-group-addon
      %i Начало взаимодействия:
    = f.text_field :start_date, class: "form-control"
    %span.input-group-addon
      %i Окончание взаимодействия:
    = f.text_field :end_date, class: "form-control"

  = f.submit 'Сохранить', :class => 'btn btn-primary btn-sm'


:coffeescript
  $('#truck_driver_start_date').datetimepicker timepicker: true
  $('#truck_driver_end_date').datetimepicker timepicker: true

app/views/transports/_show_drivers.html.haml
- if @truck
  - unless @truck.chained_truck_drivers.any?
    = link_to new_and_edit_driver_transport_path(@truck), class: 'btn btn-primary btn-xs', remote: true do
      %span.glyphicon.glyphicon-plus 
        Добавить связку водитель-тягач
  - if @truck_drivers.any?
    %table
      %thead
        %tr
          %th Тягач
          %th Водитель
          %th С:
          %th По:
          %th
          %th
      %tbody
        - @truck_drivers.each do |truck_driver|
          %tr{:class => "#{'select_green' if truck_driver.chained?}"}
            %td= truck_driver.transport.reg_num if truck_driver.transport 
            %td= truck_driver.employee.person_info if truck_driver.employee
            %td= truck_driver.start_date 
            %td= truck_driver.end_date
            %td.edit{:title => "Редатировать"}= link_to image_tag("edit.png"), new_and_edit_driver_transport_path(@truck, truck_driver: truck_driver.id), remote: true if truck_driver.chained?
            %td.del{:title => "Расцепить"}
              - if truck_driver.chained?
                = link_to unchain_driver_transport_path(truck_driver), data: { confirm: 'Точно расцепить?' }, remote: true do
                  %span.glyphicon.glyphicon-random 

app/views/transports/_transportloadings.erb
<% transportloadings.each do |loading|  %>
<%= loading.loading %>,
<% end %>

app/views/transports/edit.html.haml
.page-header
  %h2 Редактирование #{@transport.truck? ? 'тягача' : 'прицепа'}

#form.col-md-10.col-md-offset-1
  - if @transport.truck?
    = render 'form_truck' 
  - else  
    = render 'form_trailer'

app/views/transports/index.html.haml
.page-header
  %h2 Транспортные средства

.col-md-10.col-md-offset-1

  .well.well-sm 
    = link_to 'Новый тягач', new_transport_path(ts: 'truck'), class: "btn btn-primary btn-sm"
    = link_to 'Новый прицеп', new_transport_path(ts: 'trailer'), class: "btn btn-default btn-sm"
    = link_to params[:showdel] == "true" ? "Скрыть удаленные" : "Показать удаленные", transports_path(showdel: params[:showdel] == "true" ? "false" : "true") , class: "btn btn-warning btn-sm pull-right"

  %table#transports
    %thead>
      %tr
        %th Рег. номер
        %th Контрагент
        %th Марка
        %th Модель
        %th VIN номер
        %th Дата регистрации
        %th Описание
        %th Дата вывода из эксплуатации
        %th Документ
        /%th 
        %th 
        %th 
        %th 
    %tbody
      - @transports.each do |transport| 
        %tr
          %td
            = transport.reg_num 
            - if transport.is_close 
              %span.red удалено 
          %td= transport.contractor.short_name if transport.contractor 
          %td= transport.transportmodel.transportbrand.name if transport.transportmodel and transport.transportmodel.transportbrand
          %td= transport.transportmodel.name if transport.transportmodel 
          %td= transport.vin
          %td= transport.created_at.strftime("%d.%m.%Y")
          %td= transport.description 
          %td= transport.decommissioning_date.strftime("%d.%m.%Y") unless transport.decommissioning_date.blank?
          %td= transport.documents.any? ? "Есть" : "Нет"
          /%td.docs{:title => "Документы"}= link_to image_tag("docs.png"), action: "show_part", id: transport, part: transport.documents.any? ? "docs" : "select_new_document", id: transport, remote: true
          %td.copy= link_to image_tag("copy.png", title: "Редактировать копию ТС"), edit_transport_path(transport, copy: "true"), data: { confirm: 'Создать копию ТС?' } unless transport.inside_contractor?
          %td.edit= link_to image_tag("edit.png", title: "Редактировать"), edit_transport_path(transport) unless transport.inside_contractor?
          %td.del{:title => "Удалить"}= link_to image_tag("remove.png", title: "Удалить"), transport, method: :delete, data: { confirm: 'Точно?' } unless transport.is_close unless transport.inside_contractor?

app/views/transports/new_and_edit_coupler.js.haml
$("#popup_content").html("#{j render 'new_and_edit_coupler' }");
$("#popup_head span").html("Новая сцепка. Тягач: #{j @truck.reg_num }");
$("#popup").show();

app/views/transports/new_and_edit_driver.js.haml
$("#popup_content").html("#{j render 'new_and_edit_driver' }");
$("#popup_head span").html("Новая связка. Тягач: #{j @truck.reg_num }");
$("#popup").show();

app/views/transports/show.html.erb
<h1>Транспортное средство</h1>

<table border="1">
  <tr>  <th>Название</th>               <td><%= @transport.name %></td></tr>
  <tr>  <th>Описание</th>               <td><%= @transport.description %></td></tr>
  <tr>  <th>Марка и модель</th>         <td><%= render partial: "transport_brand", object: @transport %></td></tr>

  <tr>  <th>Категория ТС</th>           <td><div id="transportcategory"><%= @category %></div></td></tr>
  <tr>  <th>Тип ТС</th>                 <td><div id="transporttype"><%= @type %></div></td></tr>
  <tr>  <th>Вид ТС</th>                 <td><div id="transportkind"><%= @kind %></div></td></tr>

  <tr>  <th>Цвет</th>                   <td><%= render partial: "transport_color", object: @transport %></td></tr>
  <tr>  <th>Год выпуска</th>            <td><%= @transport.year %></td></tr>
  <tr>  <th>VIN номер</th>              <td><%= @transport.vin %></td></tr>
  <tr>  <th>Номер шасси</th>            <td><%= @transport.chassis_num %></td></tr>
  <tr>  <th>Номер кузова</th>           <td><%= @transport.body_num %></td></tr>
  <tr>  <th>Тип двигателя</th>          <td><div id="enginetype"><%= @enginetype %></div></td></tr>
  <tr>  <th>Модель двигателя</th>       <td><div id="select_enginemodel"> <%= render partial: "transport_engine", object: @transport %> </div></td></tr>
  <tr>  <th>Мощность двигателя</th>     <td><div id="power"><%=@enginemodel.power if @enginemodel%> </div></td></tr>
  <tr>  <th>Рабочий объём двигателя</th><td><div id="displacement"><%=@enginemodel.displacement if @enginemodel%></div></td>  </tr>
  <tr>  <th>Наличие погрузки </th>      <td><div id="is_loading"><%= if @transportloadings then "да" else "нет" end  %> </div></td></tr>
  <tr>  <th>Способ погрузки</th>        <td><div id="loading"> <%= render partial: "transportloadings", object: @transportloadings if @transportloadings %></div>
                                        </td></tr>
  <tr>  <th>Наличие топливного бака</th> <td><div id="is_fuelling"><%= if @transportfuellings then "да" else "нет" end  %></div></td></tr>
  <tr>  <th>Топливный бак</th>       <td><div id="tank">
                                            <%= render partial: "transportfuellings", object: @transportfuellings if @transportfuellings %>
                                            </div>
                                        </td></tr>

  <tr>  <th colspan="2"><%= link_to 'Редактировать', edit_transport_path(@transport) %>
    <%= link_to 'Удалить', @transport, method: :delete, data: { confirm: 'Точно?' } %></th>
  </tr>

</table>

<br />

<%= link_to 'Новое ТС', new_transport_path %> | 
<%= link_to 'К транспортным средствам', transports_path %>