config/routes.rb
Rails.application.routes.draw do
  
  
  post 'status_ts_ol/create_comment_ol'
  get 'status_ts_ol/index'
  delete 'status_ts_ol/index'

  get 'status_ts/index'
  delete 'status_ts/index'
  get 'status_ts/show_filter_and_search'

  get 'proposal/cancels'
  post 'proposal/cancels'
  delete 'proposal/cancels'
  get 'proposal/works_dt'
  get 'proposal/works'
  get 'proposal/set_work'
  get 'proposal/job_requests'
  post 'proposal/set_work'
  delete 'proposal/set_work'
  get 'proposal/work_locations'
  get 'proposal/index'
  get 'proposal/show_entry_cancels'
  get 'proposal/show_work_cancels'
  get 'proposal/entries'
  get 'proposal/add_city_to_entry'
  get 'proposal/set_entry'
  post 'proposal/set_entry'
  delete 'proposal/set_entry'
  get 'proposal/set_reason'
  get 'proposal/add_cancel_to_reason'
  post 'proposal/set_reason'
  delete 'proposal/set_reason'
  get 'proposal/set_deps_reason'
  post 'proposal/set_deps_reason'
  delete 'proposal/set_deps_reason'

  get 'tariff_calculator/all_tariffs'
  post 'tariff_calculator/all_tariffs'
  get 'tariff_calculator/get_cities'
  get 'tariff_calculator/market'
  post 'tariff_calculator/market_get_tariff_grid'
  get 'tariff_calculator/edit_current_market_tariff'
  post 'tariff_calculator/save_current_market_tariff'
  delete 'tariff_calculator/destroy_current_market_tariff'
  get 'tariff_calculator/average'
  get 'tariff_calculator/average_active_regions'
  get 'tariff_calculator/average_active_cities'
  get 'tariff_calculator/set_seasons'
  post 'tariff_calculator/set_seasons'
  get 'tariff_calculator/zero'

  get 'truck_responsibles/index'
  get 'truck_responsibles/show_responsibles'
  get 'truck_responsibles/delete_responsible'
  get 'truck_responsibles/new_or_edit'
  post 'truck_responsibles/create_or_update'

  resources :modulators, except: [:show] do
    collection do
      post 'set_date'
    end
  end

  resources :extra_spendings do
    collection do
      get 'get_truck_and_payments'
      get 'payments'
      post 'payments'
      post 'set_date'
      get 'set_date'
    end
  end

  resources :extra_spending_types, except: [:show]

  resources :time_zones

  get 'reports/ts_spb'
  get 'reports/operation_log'

  post 'save_reports_xls/index'

  resources :gps_nav_transports do
    member do
      get 'show_gps_nav'
      get 'unchain_gps_nav'
    end
  end

  resources :transportmodel1cs

  resources :resource_characteristic_values

  resources :vacations do
    collection do
      get 'index'
      get 'get_form'
      post 'index'
    end
  end

  resources :booking_histories

  resources :contacts, except: [:show]

  resources :contact_types, except: [:show]

  resources :bookings do
    collection do
      get 'get_bookings'
      get 'transport_planning'
      get 'open_orders'
      get 'planned'
      get 'characteristic_val'
      get 'save_param'
      delete 'save_param'
      get 'show_filter_and_search'
      get 'select_filter'
      get 'save_xls'
      get 'select_truck'
      get 'empty_mileage'
      get 'get_city_locations'
      post 'save_empty_mileage'
      post 'save_truck'
      get 'get_column_values'
    end  
  end

  resources :booking_types

  resources :contractor_responsibles, except: [:show] do
    member do
      get 'show_responsibles'
      get 'unchain_responsible'
    end
  end

  resources :properties

  resources :monitoring_connections, only: [:index] do
    collection do
      get 'save_param'      
      delete 'save_param'
      get 'select_filter'
      post 'index'
      post 'create_comment'
      post 'agree'
      post 'quick_agree'
      delete 'quick_disagree'      
      delete 'disagree'
    end
  end

  
  get 'monitoring_resource_unavailable/index', as: :monitoring_resource_unavailable
  post 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/save_xls'

  get 'monitoring_fuel_stations/index', as: :monitoring_fuel_stations
  post 'monitoring_fuel_stations/index'
  get 'monitoring_fuel_stations/save_xls'
  post 'monitoring_fuel_stations/save_reports_xls'
  post 'monitoring_fuel_stations/refuellings'
  get 'monitoring_fuel_stations/info_by_azs_name'
  get 'monitoring_fuel_stations/expensive_refuellings'
  post 'monitoring_fuel_stations/expensive_refuellings'

  get 'uploadings/index'
  post 'uploadings/index'
  get 'uploadings/save_param'
  get 'uploadings/show_filter_and_search'

  resources :stream, only: [:uploading]

  get 'contractor_reports/save_xls'
  get 'contractor_reports/report_info'
  get 'contractor_reports/report'
  get 'contractor_reports/index'
  post 'contractor_reports/show'

  resources :contractor_analysis_parameter_changes

  resources :contractor_analysis_parameters

  resources :truck_comments

  get 'api/prm_questions'
  get 'api/show_question'
  get 'api/show_prm_question'
  post 'api/reply_prm'
  get 'api/reply'
  post 'api/send_answer'
  post 'api/send_open_answer'
  post 'api/get_azs'
  post 'api/set_azs'

  get 'payslips/index'
  post 'payslips/show'

  resources :question_answers

  resources :agreement_requests do
    collection do
      post 'index'
      get 'index'
    end
  end

  resources :agreement_accesses, except: [:show]

  resources :agreements, except: [:show]

  resources :process_statuses

  resources :task_statuses

  resources :task_action_accesses

  resources :process_action_accesses

  resources :template_steps

  resources :process_actions

  resources :task_actions

  resources :process_templates

  resources :process_types

  resources :citizenships

  resources :task_templates

  resources :task_types

  resources :contract_relationships

  resources :contracts

  resources :contract_kind_roles

  resources :contract_subkinds

  resources :contract_kinds

  resources :contract_types

  resources :contractor_representatives

  resources :unv_comments

  resources :truck_drivers, except: [:show] do
    collection do
      post 'index'
    end
  end

  resources :couplers do
    member do
      get 'unchain'
    end
  end

  resources :unv_employees

  resources :resourse_types

  resources :unv_types

  resources :employee_histories

  resources :employees
  post "employees/index"

  resources :staff_units

  resources :departments do

  end

  get "unavailables/index" => "unavailables#index"
  get "unavailables/ol" => "unavailables#ol"
  get "unavailables/connections" => "unavailables#connections"
  post "unavailables/index" => "unavailables#index"
  post "unavailables/ol" => "unavailables#ol"
  post "unavailables/connections" => "unavailables#connections"
  post "unavailables/save_xls" => "unavailables#save_xls"
  post "unavailables/show_filter_and_search" => "unavailables#show_filter_and_search"
  post "unavailables/create_comment" => "unavailables#create_comment"
  post "unavailables/create_comment_ol" => "unavailables#create_comment_ol"
  post "unavailables/agree" => "unavailables#agree"
  post "unavailables/quick_agree" => "unavailables#quick_agree"
  delete "unavailables/disagree" => "unavailables#disagree"

  resources :duties do
    collection do
      get 'add_all'
    end  
  end

  resources :tables

  resources :columns

  resources :objecttypepropertycolumns

  resources :objecttypeproperties

  resources :objecttypes

  resources :systems

  resources :phoneuses

  resources :phones

  resources :positions

  resources :contractortypes

  resources :contractors

  resources :documents do
    collection do
      get 'show_part'
      post 'select_kind'
      post "new_from"
      get 'select_kind'
      get 'edit'
      delete 'del_file'
    end
  end
  post "documents/select_transport/:id" => 'documents#select_transport'

  resources :documentkinds

  resources :documenttypes

  resources :functionalgroups do
    collection do
      post 'savesort'
      get 'savesort'
      get 'update_menu'
    end
  end

  resources :people do
    collection do
      post 'phone_person'
      get 'new_person'
      get 'phone_person'
      get 'drivers'
    end
  end

  resources :transportexploitations

  resources :transporttanks

  resources :transportloadings

  resources :transportecologicals

  resources :enginemodels

  resources :enginetypes

  resources :transportkinds

  resources :transportcolors

  resources :transporttypes

  resources :transports do
    collection do
      get 'groupings'
      post 'create_and_update_coupler'
      patch 'create_and_update_coupler'
      post 'create_and_update_driver'
      patch 'create_and_update_driver'
      get 'get_transportkind'
    end
    member do
      get 'show_couplers_and_drivers'
      get 'show_couplers'
      get 'show_drivers'
      get 'new_and_edit_coupler'
      get 'unchain_coupler'
      get 'new_and_edit_driver'
      get 'unchain_driver'
    end
  end
  post "transports/select_brand/:id" => "transports#select_brand"
  post "transports/select_tank/:id" => "transports#select_tank"
  post "transports/select_color/:id" => "transports#select_color"
  post "transports/select_enginemodel/:id" => "transports#select_enginemodel"
  post "transports/select_exploitation/:id" => "transports#select_exploitation"

  get "sms/index"
  post "sms/send_sms"

  resources :testguids, as: 'tst'

  resources :temps do
    collection do
      get 'strm'
    end

  end

  resources :roles
  post "roles/select_functional/:id" => "roles#select_functional"

  get "main/index"

  root :to => 'main#index'
  get '/' => 'main#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  post 'users/select_role/:id' => "users#select_role"
  post 'users/select_f_group/:id' => "users#select_f_group"

  scope "/admin" do
    resources :users, :usergroups, :roles, :functionals
  end

app/models/vacation.rb
class Vacation < ActiveRecord::Base
  
  belongs_to :people_contractor, class_name: "PeopleContractor", foreign_key: :employee_id , primary_key: :employeeId
  has_one :person, through: :people_contractor
  
  default_scope lambda { visible }
  scope :visible, lambda { where("vacations.is_close != 1") }
  scope :drivers, lambda { joins(person: {employees: {staff_unit: :position}}).where("positions.name = ?", "Водитель") }
  
  
  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end
  
  
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  before_action :set_vacation, only: [:show, :edit, :update, :destroy]

  
  def index
    #@vacations = Vacation.all
    #@unv_employee = UnvEmployee.new
    #@unv_employee.unv_type_id = 'CE58D7F2-E69A-4F8C-8A36-92E9066B3D5E'
    #@employees = Employee.driver_expeditors
    @from = params[:from].blank? ? 3.days.ago.to_date : params[:from]
    @to = params[:to].blank? ? 3.days.since.to_date : params[:to]

    @unv_employees_not_return = UnvEmployee.where("planned_end <= ? and actual_end IS NULL", Time.now).includes(:person) 
    
    @vacations_return = Vacation.drivers.where(:"vacations.end_date" => @from.to_date..@to.to_date).includes(:person) 
    @unv_employees_leave = UnvEmployee.where(planned_start: @from.to_date..@to.to_date).includes(:person) 
     
    @vacations =Vacation.drivers.where("(vacations.start_date <= ? AND vacations.end_date >= ?) OR (vacations.start_date >= ? AND vacations.start_date <= ?) OR (vacations.end_date >= ? AND vacations.end_date <= ?)", @from.to_date, @to.to_date, @from.to_date, @to.to_date,  @from.to_date, @to.to_date).includes(:person)
    @unv_employees = UnvEmployee.where("(planned_start <= ? AND planned_end >= ?) OR (planned_start >= ? AND planned_start <= ?) OR (planned_end <= ? AND planned_end >= ?)", @from.to_date, @to.to_date, @from.to_date, @to.to_date, @from.to_date, @to.to_date).includes(:person)
    
  end

  def show
  end

  def new
    @vacation = Vacation.new
  end

  def edit
  end

  def create
    @vacation = Vacation.new(vacation_params)

    if @vacation.save
      redirect_to vacations_url, notice: 'Отпуск добавлен'
    else
      render :new
    end
  end

  def update
    if @vacation.update(vacation_params)
      redirect_to vacations_url, notice: 'Отпуск сохранен'
    else
      render :edit
    end
  end

  def destroy
    @vacation.destroy
    redirect_to vacations_url, notice: 'Отпуск удален'
  end
  
  def del_unv_emp
    @from = params[:from]
    @to = params[:to]
    @unv_employee = UnvEmployee.find(params[:id])
    @unv_employee.close
    index
    render :save_unv_emp
  end

  def edit_unv_emp
    @from = params[:from]
    @to = params[:to]
    @unv_employee = UnvEmployee.find(params[:id])
    #@employees = Employee.driver_expeditors.includes(:person)
  end
  
  
  def get_form
    @from = params[:from]
    @to = params[:to]
    @unv_employee = UnvEmployee.new
    @unv_employee.unv_type_id = 'CE58D7F2-E69A-4F8C-8A36-92E9066B3D5E'
    @employees = Employee.driver_expeditors.includes(:person)
  end
  
  private
  
  
  # Use callbacks to share common setup or constraints between actions.
  def set_vacation
    @vacation = Vacation.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def vacation_params
    params.require(:vacation).permit(:employee_id, :descr, :start_date, :end_date, :is_close)
  end
end

app/views/vacations/_form.html.haml
= form_for @vacation, :html => { :class => "form-horizontal" } do |f|
  -if @vacation.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@vacation.errors.count, "error")} "

      %ul
        - @vacation.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :employee_id, '', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :employee_id, :class => 'form-control'
  .form-group
    = f.label :descr, '', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :descr, :class => 'form-control'
  .form-group
    = f.label :start_date, '', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.date_select :start_date, :class => 'form-control'
  .form-group
    = f.label :end_date, '', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.date_select :end_date, :class => 'form-control'
  .form-group
    = f.label :is_close, '', :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.check_box :is_close, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Сохранить', :class => 'btn btn-primary'
      = link_to vacations_path, :class => 'btn btn-default' do
        %span.glyphicon.glyphicon-list-alt
          Вернуться

app/views/vacations/_modal.html.haml
#modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "largeModal", :role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#modal-label.modal-title Плановый отпуск
      .modal-body
        =image_tag("ajax-loader.gif")
        Загрузка водителей
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Закрыть

app/views/vacations/_unv_emp_form_js.html.haml
- if @unv_employee.errors.any?
  #error_explanation
    %h2
      Ошибок: #{@unv_employee.errors.count}
    %ul
      - @unv_employee.errors.full_messages.each do |msg|
        %li= msg

= form_for @unv_employee, remote: true, html: { class: "form-horizontal" } do |f|
  = f.hidden_field :unv_type_id
  = f.hidden_field :from, value: @from
  = f.hidden_field :to, value: @to
  - if @unv_employee.new_record?
    .form-group
      = f.label :employee_id, "Водитель", class: 'col-sm-4 control-label'
      .col-sm-8
        = f.collection_select( :employee_id, @employees, :id, :person_fullname, {prompt: "Выберите водителя"}) 
  - else
    .form-group
      .alert.alert-info= @unv_employee.person.fullname
  .form-group
    = f.label :planned_start, "Запланированное начало", class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :planned_start, :class => 'form-control', size: 10
  .form-group
    = f.label :planned_end, "Запланированное окончание", :class => 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :planned_end, :class => 'form-control', size: 10
  .form-group
    = f.label :actual_end, "Фактическое окончание", class: 'col-sm-4 control-label'
    .col-sm-4
      = f.text_field :actual_end, :class => 'form-control', size: 10
  .form-group
    = f.label :descr, "Комментарий", :class => 'col-sm-4 control-label'
    .col-sm-4
      = f.text_area :descr, :class => 'form-control'
  .form-group
    .col-sm-offset-4.col-sm-8
      = f.submit 'Сохранить', :class => 'btn btn-primary'

:coffeescript
  $('#unv_employee_planned_start').datetimepicker format:'d/m/Y'
  $('#unv_employee_planned_end').datetimepicker format:'d/m/Y'
  $('#unv_employee_actual_end').datetimepicker format:'d/m/Y'
  $(".form-horizontal").submit ->
    $("#modal").modal("hide");
    return

 

app/views/vacations/_vacations.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover#vacations
    %thead
      %tr
        %th Тип
        %th Сотрудник
        %th Тягач
        %th Дата начала
        %th Дата окончания
        %th Комментарий
        %th Уволен
        %th
        %th
          
    %tbody
      - @vacations.each do |vacation|
        %tr
          %td Фактический отпуск
          %td= vacation.person.fullname
          %td= vacation.person.truck(vacation.start_date)
          %td= vacation.start_date.strftime("%d.%m.%Y")
          %td= vacation.end_date.strftime("%d.%m.%Y")
          %td
          %td= 'уволен' if vacation.person.dismissed?
          %td
          %td
      - @unv_employees.each_with_index do |unv_employee, ind|
        %tr{:id => "#{unv_employee.id}", :title => "#{unv_employee.descr}"}
          %td Плановый отпуск
          %td= unv_employee.person.fullname
          %td= unv_employee.person.truck(unv_employee.planned_start)
          %td= unv_employee.planned_start.strftime("%d.%m.%Y")
          %td= unv_employee.planned_end.strftime("%d.%m.%Y")
          %td= unv_employee.descr
          %td= 'уволен' if unv_employee.person.dismissed?
          %td.edit= link_to image_tag("edit.png"), {controller: :vacations, action: :edit_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true unless unv_employee.person.dismissed?
          %td.del= link_to image_tag("remove.png"), {controller: :vacations, action: :del_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true, data: { confirm: 'Точно?', toggle: "modal" } unless unv_employee.person.dismissed?

app/views/vacations/_vacations_leave.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover#vacations_leave
    %thead
      %tr
        %th Тип
        %th Сотрудник
        %th Тягач
        %th Дата начала
        %th Дата окончания
        %th Комментарий
        %th Уволен
        %th
        %th
    %tbody
      - @unv_employees_leave.each_with_index do |unv_employee, ind|
        %tr
          %td Плановый отпуск
          %td= unv_employee.person.fullname
          %td= unv_employee.person.truck(unv_employee.planned_start)
          %td= unv_employee.planned_start.strftime("%d.%m.%Y")
          %td= unv_employee.planned_end.strftime("%d.%m.%Y")
          %td= unv_employee.descr
          %td= 'уволен' if unv_employee.person.dismissed?
          %td.edit= link_to image_tag("edit.png"), {controller: :vacations, action: :edit_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true unless unv_employee.person.dismissed?
          %td.del= link_to image_tag("remove.png"), {controller: :vacations, action: :del_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true, data: { confirm: 'Точно?', toggle: "modal" } unless unv_employee.person.dismissed?

app/views/vacations/_vacations_not_return.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover#unv_employees_not_return
    %thead
      %tr
        %th Тип
        %th Сотрудник
        %th Тягач
        %th Дата начала
        %th Дата окончания
        %th Комментарий
        %th Уволен
        %th
        %th
    %tbody
      - @unv_employees_not_return.each_with_index do |unv_employee, ind|
        %tr
          %td Плановый отпуск
          %td= unv_employee.person.fullname
          %td= unv_employee.person.truck(unv_employee.planned_start)
          %td= unv_employee.planned_start.strftime("%d.%m.%Y")
          %td= unv_employee.planned_end.strftime("%d.%m.%Y")
          %td= unv_employee.descr
          %td= 'уволен' if unv_employee.person.dismissed?
          %td.edit= link_to image_tag("edit.png"), {controller: :vacations, action: :edit_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true unless unv_employee.person.dismissed?
          %td.del= link_to image_tag("remove.png"), {controller: :vacations, action: :del_unv_emp, id: unv_employee.id, from: @from, to: @to}, remote: true, data: { confirm: 'Точно?', toggle: "modal" } unless unv_employee.person.dismissed?

app/views/vacations/_vacations_return.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover#vacations_return
    %thead
      %tr
        %th Тип
        %th Сотрудник
        %th Тягач
        %th Уволен
        %th Дата начала
        %th Дата окончания

    %tbody
      - @vacations_return.each do |vacation|
        %tr
          %td Фактический отпуск
          %td= vacation.person.fullname
          %td= vacation.person.truck(vacation.start_date)
          %td= 'уволен' if vacation.person.dismissed?
          %td= vacation.start_date.strftime("%d.%m.%Y")
          %td= vacation.end_date.strftime("%d.%m.%Y")

app/views/vacations/edit.html.haml
.page-header

  %h2 Редактирование vacation

= render 'form'

app/views/vacations/edit_unv_emp.js.haml
$('.modal-body').html("#{j render 'vacations/unv_emp_form_js'}");
$('#modal').modal('show');

app/views/vacations/error_save_unv_emp.js.haml
$('.modal-body').html("#{j render 'vacations/unv_emp_form_js'}")

app/views/vacations/get_form.js.haml
$('.modal-body').html("#{j render 'vacations/unv_emp_form_js'}");

app/views/vacations/index.html.haml
= render 'modal'

.page-header
  %h2 
    Отпуски сотрудников
    %a.btn.btn-sm.btn-success.pull-left#to_modal
      %span.glyphicon.glyphicon-plus Плановый отпуск

= select_date_from_to

#vacations_index.col-md-10.col-md-offset-1
  .panel.panel-default
    .panel-heading
      %ul.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#all"} Все
        %li
          %a{"data-toggle" => "tab", :href => "#leave"} Уходящие в отпуск
        %li
          %a{"data-toggle" => "tab", :href => "#return"} Возвращающиеся из отпуска
        %li
          %a{"data-toggle" => "tab", :href => "#not_return"} Не вернувшиеся из отпуска
    .panel-body
      .tab-content
        #all.tab-pane.active= render 'vacations/vacations'
        #leave.tab-pane= render 'vacations/vacations_leave'
        #return.tab-pane= render 'vacations/vacations_return'
        #not_return.tab-pane= render 'vacations/vacations_not_return'


:coffeescript
  $("#to_modal").click ->
    $(".modal-body").html "<img src='/assets/ajax-loader.gif'> Загрузка водителей"
    $.get "/vacations/get_form",
      from: '#{@from}'
      to: '#{@to}'

    $("#modal").modal "show"
  return

app/views/vacations/new.html.haml
.page-header
  %h2 Новый vacation

= render 'form'

app/views/vacations/save_unv_emp.js.haml
$('#modal').modal('hide');
$('#all').html('#{j render 'vacations/vacations'}');
$('#leave').html('#{j render 'vacations/vacations_leave'}');
$('#return').html('#{j render 'vacations/vacations_return'}');

$("#vacations").dataTable({"order" : [[3, "desc"]], "lengthMenu" : [[30, 60, 100, -1], [30, 60, 100, "Все"]], "columnDefs" : [{"type" : 'date-euro', "targets" : [3, 4]}]})
$("#vacations_leave").dataTable({"order" : [[3, "desc"]], "lengthMenu" : [[30, 60, 100, -1], [30, 60, 100, "Все"]], "columnDefs" : [{"type" : 'date-euro', "targets" : [3, 4]}]})
$("#vacations_return").dataTable({"order" : [[4, "desc"]], "lengthMenu" : [[30, 60, 100, -1], [30, 60, 100, "Все"]], "columnDefs" : [{"type" : 'date-euro', "targets" : [4, 5]}]})