config/routes.rb
Rails.application.routes.draw do
  
  
  post 'status_ts_ol/create_comment_ol'
  get 'status_ts_ol/index'
  delete 'status_ts_ol/index'

  get 'status_ts/index'
  delete 'status_ts/index'
  get 'status_ts/show_filter_and_search'

  get 'proposal/cancels'
  post 'proposal/cancels'
  delete 'proposal/cancels'
  get 'proposal/works_dt'
  get 'proposal/works'
  get 'proposal/set_work'
  get 'proposal/job_requests'
  post 'proposal/set_work'
  delete 'proposal/set_work'
  get 'proposal/work_locations'
  get 'proposal/index'
  get 'proposal/show_entry_cancels'
  get 'proposal/show_work_cancels'
  get 'proposal/entries'
  get 'proposal/add_city_to_entry'
  get 'proposal/set_entry'
  post 'proposal/set_entry'
  delete 'proposal/set_entry'
  get 'proposal/set_reason'
  get 'proposal/add_cancel_to_reason'
  post 'proposal/set_reason'
  delete 'proposal/set_reason'
  get 'proposal/set_deps_reason'
  post 'proposal/set_deps_reason'
  delete 'proposal/set_deps_reason'

  get 'tariff_calculator/all_tariffs'
  post 'tariff_calculator/all_tariffs'
  get 'tariff_calculator/get_cities'
  get 'tariff_calculator/market'
  post 'tariff_calculator/market_get_tariff_grid'
  get 'tariff_calculator/edit_current_market_tariff'
  post 'tariff_calculator/save_current_market_tariff'
  delete 'tariff_calculator/destroy_current_market_tariff'
  get 'tariff_calculator/average'
  get 'tariff_calculator/average_active_regions'
  get 'tariff_calculator/average_active_cities'
  get 'tariff_calculator/set_seasons'
  post 'tariff_calculator/set_seasons'
  get 'tariff_calculator/zero'

  get 'truck_responsibles/index'
  get 'truck_responsibles/show_responsibles'
  get 'truck_responsibles/delete_responsible'
  get 'truck_responsibles/new_or_edit'
  post 'truck_responsibles/create_or_update'

  resources :modulators, except: [:show] do
    collection do
      post 'set_date'
    end
  end

  resources :extra_spendings do
    collection do
      get 'get_truck_and_payments'
      get 'payments'
      post 'payments'
      post 'set_date'
      get 'set_date'
    end
  end

  resources :extra_spending_types, except: [:show]

  resources :time_zones

  get 'reports/ts_spb'
  get 'reports/operation_log'

  post 'save_reports_xls/index'

  resources :gps_nav_transports do
    member do
      get 'show_gps_nav'
      get 'unchain_gps_nav'
    end
  end

  resources :transportmodel1cs

  resources :resource_characteristic_values

  resources :vacations do
    collection do
      get 'index'
      get 'get_form'
      post 'index'
    end
  end

  resources :booking_histories

  resources :contacts, except: [:show]

  resources :contact_types, except: [:show]

  resources :bookings do
    collection do
      get 'get_bookings'
      get 'transport_planning'
      get 'open_orders'
      get 'planned'
      get 'characteristic_val'
      get 'save_param'
      delete 'save_param'
      get 'show_filter_and_search'
      get 'select_filter'
      get 'save_xls'
      get 'select_truck'
      get 'empty_mileage'
      get 'get_city_locations'
      post 'save_empty_mileage'
      post 'save_truck'
      get 'get_column_values'
    end  
  end

  resources :booking_types

  resources :contractor_responsibles, except: [:show] do
    member do
      get 'show_responsibles'
      get 'unchain_responsible'
    end
  end

  resources :properties

  resources :monitoring_connections, only: [:index] do
    collection do
      get 'save_param'      
      delete 'save_param'
      get 'select_filter'
      post 'index'
      post 'create_comment'
      post 'agree'
      post 'quick_agree'
      delete 'quick_disagree'      
      delete 'disagree'
    end
  end

  
  get 'monitoring_resource_unavailable/index', as: :monitoring_resource_unavailable
  post 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/save_xls'

  get 'monitoring_fuel_stations/index', as: :monitoring_fuel_stations
  post 'monitoring_fuel_stations/index'
  get 'monitoring_fuel_stations/save_xls'
  post 'monitoring_fuel_stations/save_reports_xls'
  post 'monitoring_fuel_stations/refuellings'
  get 'monitoring_fuel_stations/info_by_azs_name'
  get 'monitoring_fuel_stations/expensive_refuellings'
  post 'monitoring_fuel_stations/expensive_refuellings'

  get 'uploadings/index'
  post 'uploadings/index'
  get 'uploadings/save_param'
  get 'uploadings/show_filter_and_search'

  resources :stream, only: [:uploading]

  get 'contractor_reports/save_xls'
  get 'contractor_reports/report_info'
  get 'contractor_reports/report'
  get 'contractor_reports/index'
  post 'contractor_reports/show'

  resources :contractor_analysis_parameter_changes

  resources :contractor_analysis_parameters

  resources :truck_comments

  get 'api/prm_questions'
  get 'api/show_question'
  get 'api/show_prm_question'
  post 'api/reply_prm'
  get 'api/reply'
  post 'api/send_answer'
  post 'api/send_open_answer'
  post 'api/get_azs'
  post 'api/set_azs'

  get 'payslips/index'
  post 'payslips/show'

  resources :question_answers

  resources :agreement_requests do
    collection do
      post 'index'
      get 'index'
    end
  end

  resources :agreement_accesses, except: [:show]

  resources :agreements, except: [:show]

  resources :process_statuses

  resources :task_statuses

  resources :task_action_accesses

  resources :process_action_accesses

  resources :template_steps

  resources :process_actions

  resources :task_actions

  resources :process_templates

  resources :process_types

  resources :citizenships

  resources :task_templates

  resources :task_types

  resources :contract_relationships

  resources :contracts

  resources :contract_kind_roles

  resources :contract_subkinds

  resources :contract_kinds

  resources :contract_types

  resources :contractor_representatives

  resources :unv_comments

  resources :truck_drivers, except: [:show] do
    collection do
      post 'index'
    end
  end

  resources :couplers do
    member do
      get 'unchain'
    end
  end

  resources :unv_employees

  resources :resourse_types

  resources :unv_types

  resources :employee_histories

  resources :employees
  post "employees/index"

  resources :staff_units

  resources :departments do

  end

  get "unavailables/index" => "unavailables#index"
  get "unavailables/ol" => "unavailables#ol"
  get "unavailables/connections" => "unavailables#connections"
  post "unavailables/index" => "unavailables#index"
  post "unavailables/ol" => "unavailables#ol"
  post "unavailables/connections" => "unavailables#connections"
  post "unavailables/save_xls" => "unavailables#save_xls"
  post "unavailables/show_filter_and_search" => "unavailables#show_filter_and_search"
  post "unavailables/create_comment" => "unavailables#create_comment"
  post "unavailables/create_comment_ol" => "unavailables#create_comment_ol"
  post "unavailables/agree" => "unavailables#agree"
  post "unavailables/quick_agree" => "unavailables#quick_agree"
  delete "unavailables/disagree" => "unavailables#disagree"

  resources :duties do
    collection do
      get 'add_all'
    end  
  end

  resources :tables

  resources :columns

  resources :objecttypepropertycolumns

  resources :objecttypeproperties

  resources :objecttypes

  resources :systems

  resources :phoneuses

  resources :phones

  resources :positions

  resources :contractortypes

  resources :contractors

  resources :documents do
    collection do
      get 'show_part'
      post 'select_kind'
      post "new_from"
      get 'select_kind'
      get 'edit'
      delete 'del_file'
    end
  end
  post "documents/select_transport/:id" => 'documents#select_transport'

  resources :documentkinds

  resources :documenttypes

  resources :functionalgroups do
    collection do
      post 'savesort'
      get 'savesort'
      get 'update_menu'
    end
  end

  resources :people do
    collection do
      post 'phone_person'
      get 'new_person'
      get 'phone_person'
      get 'drivers'
    end
  end

  resources :transportexploitations

  resources :transporttanks

  resources :transportloadings

  resources :transportecologicals

  resources :enginemodels

  resources :enginetypes

  resources :transportkinds

  resources :transportcolors

  resources :transporttypes

  resources :transports do
    collection do
      get 'groupings'
      post 'create_and_update_coupler'
      patch 'create_and_update_coupler'
      post 'create_and_update_driver'
      patch 'create_and_update_driver'
      get 'get_transportkind'
    end
    member do
      get 'show_couplers_and_drivers'
      get 'show_couplers'
      get 'show_drivers'
      get 'new_and_edit_coupler'
      get 'unchain_coupler'
      get 'new_and_edit_driver'
      get 'unchain_driver'
    end
  end
  post "transports/select_brand/:id" => "transports#select_brand"
  post "transports/select_tank/:id" => "transports#select_tank"
  post "transports/select_color/:id" => "transports#select_color"
  post "transports/select_enginemodel/:id" => "transports#select_enginemodel"
  post "transports/select_exploitation/:id" => "transports#select_exploitation"

  get "sms/index"
  post "sms/send_sms"

  resources :testguids, as: 'tst'

  resources :temps do
    collection do
      get 'strm'
    end

  end

  resources :roles
  post "roles/select_functional/:id" => "roles#select_functional"

  get "main/index"

  root :to => 'main#index'
  get '/' => 'main#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  post 'users/select_role/:id' => "users#select_role"
  post 'users/select_f_group/:id' => "users#select_f_group"

  scope "/admin" do
    resources :users, :usergroups, :roles, :functionals
  end

app/models/staff_unit.rb
# -*- encoding : utf-8 -*-
class StaffUnit < ActiveRecord::Base
  #  attr_accessible :department_id, :descr, :head, :id, :position_id, :is_close, :rgt, :lft, :parent_id

  belongs_to :department
  belongs_to :position
  has_many :employees
  has_many :process_action_accesses
  has_many :task_action_accesses
  has_many :agreement_accesses

  #audited

  #acts_as_nested_set

  before_validation :ensure_uuid #, :delete_empty_parameters

  validates :department_id, :descr, :position_id, presence: true

  scope :visible, lambda { where("is_close != ?", true) }
  scope :heads, lambda { where("head = ?", true).visible }


  #  def employee #переопределение
  #    self.is_close ? nil : super
  #  end

#  def employees #переопределение
#    super.visible
#  end

  def employees_persons
    self.employees.map { |p| p.person  }
  end

  def contractor
    self.department and self.department.contractor ? self.department.contractor : false
  end

  def cdp #contractor + department + position
    contractor and position ?  "Контрагент: #{department.contractor.name}. Подразделение:#{department.name}. Должность: #{position.name}." : nil
  end

  def position_name #contractor + department + position
   position ?  position.name : nil
  end

  #  def self.free_units
  #    self.visible.find_all{|f| !f.employee}.sort_by(&:cdp).compact
  #  end


  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end


  private


  def ensure_uuid
    self.id ||= SecureRandom.uuid
  end

  def delete_empty_parameters
    Department.accessible_attributes.each do |c|
      self[c.to_sym] = nil if self[c.to_sym].blank? and  c!= 'is_close'
    end
  end


end

app/controllers/staff_units_controller.rb
# -*- encoding : utf-8 -*-

class StaffUnitsController < ApplicationController


  def index
    #@contractors = Contractor.find(Department.select('distinct contractor_id').map(&:contractor_id))
    @contractors = Contractor.includes(:departments)
    @departments = Department.visible.order(:name)
    
    @staff_units_count = StaffUnit.count

    unless params[:contractor].blank?
      @contractor = Contractor.find(params[:contractor])
      unless params[:department].blank?
        @department = Department.find(params[:department])
        @staff_units = @department.staff_units.sort { |a, b| a.department <=> b.department }#.paginate(page: params[:page], per_page: 20)
      else
        @staff_units = @contractor.staff_units.sort { |a, b| a.department <=> b.department }#.paginate(page: params[:page], per_page: 20)
      end
    else
      @staff_units = StaffUnit.joins(:department).order('departments.name, staff_units.position_id ')#.paginate(page: params[:page], per_page: 20)
    end



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staff_units }
    end
  end


  def show
    @staff_unit = StaffUnit.find(params[:id])

    respond_to do |format|
      format.js {}
    end
    
  end


  def new
    @staff_unit = StaffUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff_unit }
    end
  end


  def edit
    @staff_unit = StaffUnit.find(params[:id])
  end


  def create
    @staff_unit = StaffUnit.new(staff_unit_params)

    respond_to do |format|
      if @staff_unit.save
        format.html { redirect_to staff_units_url, notice: 'Штатная единица добавлена' }
        format.json { render json: @staff_unit, status: :created, location: @staff_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @staff_unit.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @staff_unit = StaffUnit.find(params[:id])

    respond_to do |format|
      if @staff_unit.update_attributes(staff_unit_params)
        format.html { redirect_to staff_units_url, notice: 'Штатная единица сохранена' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff_unit.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @staff_unit = StaffUnit.find(params[:id])
    @staff_unit.close

    respond_to do |format|
      format.html { redirect_to staff_units_url }
      format.json { head :no_content }
    end
  end


 private

 def staff_unit_params
   params[:staff_unit].each do |k,v|
       params[:staff_unit][k.to_sym] = nil if params[:staff_unit][k.to_sym].blank? and  k!= 'is_close'
   end
   params.require(:staff_unit).permit(:department_id, :descr, :head, :id, :position_id, :is_close, :rgt, :lft, :parent_id)
 end


end

app/views/staff_units/_form.html.erb
<% if @staff_unit.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибок: <%= @staff_unit.errors.count %></h2>

      <ul>
      <% @staff_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@staff_unit) do |f| %>
  <table>
    <tr>
      <th><%= f.label :department_id, "Подразделение" %></th>
      <td><%= f.collection_select( :department_id, Department.visible, :id, :contractor_name,
              { prompt: @staff_unit.department_id ? nil : "Выберите подразделение",
              selected: @staff_unit.department_id ? @staff_unit.department_id : nil}  )%>
      </td>
    </tr>
    <tr>
      <th><%= f.label :position_id, "Должность" %></th>
      <td><%= f.collection_select( :position_id, Position.visible, :id, :name,
              { prompt: @staff_unit.position_id ? nil : "Выберите должность",
              selected: @staff_unit.position_id ? @staff_unit.position_id : nil}  )%>
      </td>
    </tr>
      <th><%= f.label :parent_id, "Руководитель данной штатной единицы" %></th>
    <td> <%= f.collection_select( :parent_id, StaffUnit.heads, :id, :cdp,
                { selected: @staff_unit.parent_id ? @staff_unit.parent_id : StaffUnit.heads.first, include_blank: "Нет" } )%>
    </td>
    <tr>
      <th><%= f.label :head, "Является руководителем" %></th>
      <td><%= f.check_box :head %></td>
    </tr>
    <tr>
      <th><%= f.label :descr, "Описание функций штатной единицы" %></th>
      <td><%= f.text_area :descr %></td>
    </tr>
    <tr>
      <th><%= f.label :is_close, "Удалено" %></th>
      <td><%= f.check_box :is_close %></td>
    </tr>
    <tr>
      <th colspan="2"><%= f.submit "Сохранить" %> <%= link_to 'Вернуться', staff_units_path %></th>
    </tr>
  </table>
<% end %>

app/views/staff_units/_show.html.erb
<table>
  <tr>
    <th style="width: 200px;">Контрагент</th><td><%= @staff_unit.contractor.name if @staff_unit.contractor %></td>
  </tr>
  <tr>
    <th>Подразделение</th> <td><%= @staff_unit.department.name if @staff_unit.department %></td>
  </tr>
  <tr>
    <th>Должность</th> <td><%= @staff_unit.position.name if @staff_unit.position %></td>
  </tr>
  <tr>
    <th>Статус (руководитель/сотрудник)</th><td><%= @staff_unit.head ? "Руководитель" : "Сотрудник" %></td>
  </tr>
  <tr>
    <th>Описание должностных обязанностей</th><td><%= @staff_unit.descr %></td>
  </tr>
  <tr>
    <th>Удален</th><td style="color: red"><%= @staff_unit.is_close ? "Удален" : "" %></td>
  </tr>
  <tr>
    <th>
    <%= button_to 'Редактировать', edit_staff_unit_path(@staff_unit), method: "get" %>
    </th>
  </tr>
</table>

 

app/views/staff_units/edit.html.erb
<h2>Редактирование штатной единицы</h2>
<div id="form">
<%= render 'form' %>
</div>

app/views/staff_units/index.html.erb
<h2>Штатные единицы (<%=@staff_units_count%>)</h2>

<%#= will_paginate @staff_units, class: "apple_pagination" %>
<table>
  <tr><th><%= button_to 'Новая штатная единица', new_staff_unit_path, method: 'get' %></th>

    <%= form_tag  url_for( action: 'index'), method: :get do %>
      <td style="width: 200px;"> <%= label_tag "Контрагенты" %>
        <%= select_tag( :contractor, options_for_select(@contractors.map { |m| [m.name, m.id] }, { selected: params[:contractor].blank? ? nil : params[:contractor]}), {prompt: "Все контрагенты:"}) if @contractors.any? %> </td>
      <td style="width: 200px;"> <%= label_tag "Подразделения" %>
        <%= select_tag(:department,  options_for_select(@departments.map { |m| [m.name, m.id, { class: m.contractor_id}] }, { selected: params[:department].blank? ? nil : params[:department] }), {prompt: "Все подразделения:"}) if @departments.any? %>
        </td>
        <th style="width: 70px;">  <%= submit_tag "Выбрать", id: "submit"%> </th>
      <% end %>
    </tr>
  </table>
  <table id="staff_units">
    <thead>
      <tr>
        <th>Контрагент</th>
        <th>Подразделение</th>
        <th>Должность</th>
        <th>Статус</th>
        <th>Сотрудники</th>
        <th>Описание</th>
      </tr>
    </thead>
    <tbody>
      <% @staff_units.each do |staff_unit| %>
        <tr>
          <td <%= 'class=deleted title=Удален' if staff_unit.is_close %>><%= staff_unit.contractor.name if staff_unit.contractor%> </td>
          <td><%= staff_unit.department.name if staff_unit.department %></td>
          <td><%= staff_unit.position.name if staff_unit.position %></td>
          <td><%= staff_unit.head ? "Руководитель" : "Сотрудник" %></td>
          <td>
            <div class="btn-group" data-toggle="buttons-checkbox">
              <a class="btn collapse-data-btn" data-toggle="collapse" href="#details<%= staff_unit.id %>">Посмотреть всех</a>
            </div>
            <div id="details<%= staff_unit.id %>" class="collapse">
              <p>
                <%=raw staff_unit.employees && staff_unit.employees_persons.any? ? staff_unit.employees_persons.compact.map { |p| p.fullname }.join(', ') : '<b style="color: red;">НЕТ</b>' %>
              </p>
            </div>
            (<%= staff_unit.employees && staff_unit.employees_persons.any? ? staff_unit.employees_persons.size : 0 %>)
          </td>
          <td><%= staff_unit.descr %></td>
          <td class="show1">
            <%= link_to image_tag("show.png"), staff_unit, remote: true %>
          </td>
          <td class="edit">
            <%= link_to image_tag("edit.png"), edit_staff_unit_path(staff_unit) %>
          </td>
          <td class="del" title="Удалить">
            <%= link_to image_tag("remove.png"), staff_unit, method: :delete, data: { confirm: 'Точно?' } unless staff_unit.is_close %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <table>
    <tr><th><%= button_to 'Новая штатная единица', new_staff_unit_path, method: 'get' if @staff_units.size > 10 %></th></tr>
  </table>

  <%#= will_paginate @staff_units, class: "apple_pagination"  %>


  <script>
    $(function() {
      $("#department").chained("#contractor");
    });

  </script>

app/views/staff_units/new.html.erb
<h2>Новая штатная единица</h2>
<div id="form">
<%= render 'form' %>
</div>

app/views/staff_units/show.html.erb
<h2>Просмотр штатной единицы</h2>
<table>
  <tr>
    <th>Id:</th>
    <td><%= @staff_unit.id %></td>
  </tr>
  <tr>
    <th>Head:</th>
    <td><%= @staff_unit.head %></td>
  </tr>
  <tr>
    <th>Department:</th>
    <td><%= @staff_unit.department_id %></td>
  </tr>
  <tr>
    <th>Position:</th>
    <td><%= @staff_unit.position_id %></td>
  </tr>
  <tr>
    <th>Descr:</th>
    <td><%= @staff_unit.descr %></td>
  </tr>
  <tr>
    <th>
    <%= link_to 'Редактировать', edit_staff_unit_path(@staff_unit) %>
    <%= link_to 'Вернуться', staff_units_path %>
    </th>
  </tr>
</table>

 

app/views/staff_units/show.js.erb
$("#popup_content").html("<%=j render 'show' %>");
$("#popup_head span").html("Штатная единица");
$("#popup").show(300);