config/routes.rb
Rails.application.routes.draw do
  
  
  post 'status_ts_ol/create_comment_ol'
  get 'status_ts_ol/index'
  delete 'status_ts_ol/index'

  get 'status_ts/index'
  delete 'status_ts/index'
  get 'status_ts/show_filter_and_search'

  get 'proposal/cancels'
  post 'proposal/cancels'
  delete 'proposal/cancels'
  get 'proposal/works_dt'
  get 'proposal/works'
  get 'proposal/set_work'
  get 'proposal/job_requests'
  post 'proposal/set_work'
  delete 'proposal/set_work'
  get 'proposal/work_locations'
  get 'proposal/index'
  get 'proposal/show_entry_cancels'
  get 'proposal/show_work_cancels'
  get 'proposal/entries'
  get 'proposal/add_city_to_entry'
  get 'proposal/set_entry'
  post 'proposal/set_entry'
  delete 'proposal/set_entry'
  get 'proposal/set_reason'
  get 'proposal/add_cancel_to_reason'
  post 'proposal/set_reason'
  delete 'proposal/set_reason'
  get 'proposal/set_deps_reason'
  post 'proposal/set_deps_reason'
  delete 'proposal/set_deps_reason'

  get 'tariff_calculator/all_tariffs'
  post 'tariff_calculator/all_tariffs'
  get 'tariff_calculator/get_cities'
  get 'tariff_calculator/market'
  post 'tariff_calculator/market_get_tariff_grid'
  get 'tariff_calculator/edit_current_market_tariff'
  post 'tariff_calculator/save_current_market_tariff'
  delete 'tariff_calculator/destroy_current_market_tariff'
  get 'tariff_calculator/average'
  get 'tariff_calculator/average_active_regions'
  get 'tariff_calculator/average_active_cities'
  get 'tariff_calculator/set_seasons'
  post 'tariff_calculator/set_seasons'
  get 'tariff_calculator/zero'

  get 'truck_responsibles/index'
  get 'truck_responsibles/show_responsibles'
  get 'truck_responsibles/delete_responsible'
  get 'truck_responsibles/new_or_edit'
  post 'truck_responsibles/create_or_update'

  resources :modulators, except: [:show] do
    collection do
      post 'set_date'
    end
  end

  resources :extra_spendings do
    collection do
      get 'get_truck_and_payments'
      get 'payments'
      post 'payments'
      post 'set_date'
      get 'set_date'
    end
  end

  resources :extra_spending_types, except: [:show]

  resources :time_zones

  get 'reports/ts_spb'
  get 'reports/operation_log'

  post 'save_reports_xls/index'

  resources :gps_nav_transports do
    member do
      get 'show_gps_nav'
      get 'unchain_gps_nav'
    end
  end

  resources :transportmodel1cs

  resources :resource_characteristic_values

  resources :vacations do
    collection do
      get 'index'
      get 'get_form'
      post 'index'
    end
  end

  resources :booking_histories

  resources :contacts, except: [:show]

  resources :contact_types, except: [:show]

  resources :bookings do
    collection do
      get 'get_bookings'
      get 'transport_planning'
      get 'open_orders'
      get 'planned'
      get 'characteristic_val'
      get 'save_param'
      delete 'save_param'
      get 'show_filter_and_search'
      get 'select_filter'
      get 'save_xls'
      get 'select_truck'
      get 'empty_mileage'
      get 'get_city_locations'
      post 'save_empty_mileage'
      post 'save_truck'
      get 'get_column_values'
    end  
  end

  resources :booking_types

  resources :contractor_responsibles, except: [:show] do
    member do
      get 'show_responsibles'
      get 'unchain_responsible'
    end
  end

  resources :properties

  resources :monitoring_connections, only: [:index] do
    collection do
      get 'save_param'      
      delete 'save_param'
      get 'select_filter'
      post 'index'
      post 'create_comment'
      post 'agree'
      post 'quick_agree'
      delete 'quick_disagree'      
      delete 'disagree'
    end
  end

  
  get 'monitoring_resource_unavailable/index', as: :monitoring_resource_unavailable
  post 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/processes'
  get 'monitoring_resource_unavailable/save_xls'

  get 'monitoring_fuel_stations/index', as: :monitoring_fuel_stations
  post 'monitoring_fuel_stations/index'
  get 'monitoring_fuel_stations/save_xls'
  post 'monitoring_fuel_stations/save_reports_xls'
  post 'monitoring_fuel_stations/refuellings'
  get 'monitoring_fuel_stations/info_by_azs_name'
  get 'monitoring_fuel_stations/expensive_refuellings'
  post 'monitoring_fuel_stations/expensive_refuellings'

  get 'uploadings/index'
  post 'uploadings/index'
  get 'uploadings/save_param'
  get 'uploadings/show_filter_and_search'

  resources :stream, only: [:uploading]

  get 'contractor_reports/save_xls'
  get 'contractor_reports/report_info'
  get 'contractor_reports/report'
  get 'contractor_reports/index'
  post 'contractor_reports/show'

  resources :contractor_analysis_parameter_changes

  resources :contractor_analysis_parameters

  resources :truck_comments

  get 'api/prm_questions'
  get 'api/show_question'
  get 'api/show_prm_question'
  post 'api/reply_prm'
  get 'api/reply'
  post 'api/send_answer'
  post 'api/send_open_answer'
  post 'api/get_azs'
  post 'api/set_azs'

  get 'payslips/index'
  post 'payslips/show'

  resources :question_answers

  resources :agreement_requests do
    collection do
      post 'index'
      get 'index'
    end
  end

  resources :agreement_accesses, except: [:show]

  resources :agreements, except: [:show]

  resources :process_statuses

  resources :task_statuses

  resources :task_action_accesses

  resources :process_action_accesses

  resources :template_steps

  resources :process_actions

  resources :task_actions

  resources :process_templates

  resources :process_types

  resources :citizenships

  resources :task_templates

  resources :task_types

  resources :contract_relationships

  resources :contracts

  resources :contract_kind_roles

  resources :contract_subkinds

  resources :contract_kinds

  resources :contract_types

  resources :contractor_representatives

  resources :unv_comments

  resources :truck_drivers, except: [:show] do
    collection do
      post 'index'
    end
  end

  resources :couplers do
    member do
      get 'unchain'
    end
  end

  resources :unv_employees

  resources :resourse_types

  resources :unv_types

  resources :employee_histories

  resources :employees
  post "employees/index"

  resources :staff_units

  resources :departments do

  end

  get "unavailables/index" => "unavailables#index"
  get "unavailables/ol" => "unavailables#ol"
  get "unavailables/connections" => "unavailables#connections"
  post "unavailables/index" => "unavailables#index"
  post "unavailables/ol" => "unavailables#ol"
  post "unavailables/connections" => "unavailables#connections"
  post "unavailables/save_xls" => "unavailables#save_xls"
  post "unavailables/show_filter_and_search" => "unavailables#show_filter_and_search"
  post "unavailables/create_comment" => "unavailables#create_comment"
  post "unavailables/create_comment_ol" => "unavailables#create_comment_ol"
  post "unavailables/agree" => "unavailables#agree"
  post "unavailables/quick_agree" => "unavailables#quick_agree"
  delete "unavailables/disagree" => "unavailables#disagree"

  resources :duties do
    collection do
      get 'add_all'
    end  
  end

  resources :tables

  resources :columns

  resources :objecttypepropertycolumns

  resources :objecttypeproperties

  resources :objecttypes

  resources :systems

  resources :phoneuses

  resources :phones

  resources :positions

  resources :contractortypes

  resources :contractors

  resources :documents do
    collection do
      get 'show_part'
      post 'select_kind'
      post "new_from"
      get 'select_kind'
      get 'edit'
      delete 'del_file'
    end
  end
  post "documents/select_transport/:id" => 'documents#select_transport'

  resources :documentkinds

  resources :documenttypes

  resources :functionalgroups do
    collection do
      post 'savesort'
      get 'savesort'
      get 'update_menu'
    end
  end

  resources :people do
    collection do
      post 'phone_person'
      get 'new_person'
      get 'phone_person'
      get 'drivers'
    end
  end

  resources :transportexploitations

  resources :transporttanks

  resources :transportloadings

  resources :transportecologicals

  resources :enginemodels

  resources :enginetypes

  resources :transportkinds

  resources :transportcolors

  resources :transporttypes

  resources :transports do
    collection do
      get 'groupings'
      post 'create_and_update_coupler'
      patch 'create_and_update_coupler'
      post 'create_and_update_driver'
      patch 'create_and_update_driver'
      get 'get_transportkind'
    end
    member do
      get 'show_couplers_and_drivers'
      get 'show_couplers'
      get 'show_drivers'
      get 'new_and_edit_coupler'
      get 'unchain_coupler'
      get 'new_and_edit_driver'
      get 'unchain_driver'
    end
  end
  post "transports/select_brand/:id" => "transports#select_brand"
  post "transports/select_tank/:id" => "transports#select_tank"
  post "transports/select_color/:id" => "transports#select_color"
  post "transports/select_enginemodel/:id" => "transports#select_enginemodel"
  post "transports/select_exploitation/:id" => "transports#select_exploitation"

  get "sms/index"
  post "sms/send_sms"

  resources :testguids, as: 'tst'

  resources :temps do
    collection do
      get 'strm'
    end

  end

  resources :roles
  post "roles/select_functional/:id" => "roles#select_functional"

  get "main/index"

  root :to => 'main#index'
  get '/' => 'main#index'

  devise_for :users, :skip => [:sessions]
  as :user do
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  post 'users/select_role/:id' => "users#select_role"
  post 'users/select_f_group/:id' => "users#select_f_group"

  scope "/admin" do
    resources :users, :usergroups, :roles, :functionals
  end

app/models/gps_nav_transport.rb
class GpsNavTransport < ActiveRecord::Base
  
  validate :not_create_many_chained_gps
  validates  :start_date, :gps_nav_id, :transport_id, presence: true
  
  
  belongs_to :transport
  belongs_to :gps_nav
  belongs_to :user
  
  #default_scope lambda { visible }
  scope :visible, lambda { where("gps_nav_transports.is_close != ?", true) }
  scope :chained, lambda {visible.where("[gps_nav_transports].[end_date] > ? or [gps_nav_transports].[end_date] IS NULL", Time.now)}

 
  def unchain_gps_nav_transport
    self.update_attribute(:end_date, Time.now )
  end

  def chained?
    end_date.nil? or end_date > Time.now 
  end
  
  def close
    self.update_attribute( :is_close, true )
  end

  def unclose
    self.update_attribute( :is_close, false )
  end

  private
  
  def not_create_many_chained_gps
    @other_chained_gps = GpsNavTransport.visible.where(gps_nav_id: gps_nav_id).where("end_date IS NULL or end_date > ?", Time.now).limit 1 
    if @other_chained_gps.any? and @other_chained_gps.first.gps_nav_id != gps_nav_id and (end_date.blank? or end_date > Time.now)
        gps_error(@other_chained_gps.first.gps_nav.name) 
    end
  end

  def gps_error(gps)
    errors.add(:"Ошибка назначения связки:", "Действующая связка уже существует. GPS: #{gps}")
  end
  
  
  
end

app/controllers/gps_nav_transports_controller.rb
class GpsNavTransportsController < ApplicationController
  before_action :set_gps_nav_transport, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def index
    user_session[:gps_nav_transports] = params[:vis] unless params[:vis].blank?
    
    @trucks =
      case user_session[:gps_nav_transports]
      when 'without_gps'
        Transport.without_gps
      else
        Transport.trucks.includes(chained_gps_nav_transports: [:gps_nav, :user])
      end

  end

  def show_gps_nav
    @truck = Transport.find(params[:id])
    @gps_nav_transports = @truck.gps_nav_transports.order("created_at desc")
    respond_to do |format|
      format.js {  }
    end
  end
  
  def unchain_gps_nav
    @gps_nav_transport = GpsNavTransport.find(params[:id])
    @gps_nav_transport.unchain_gps_nav_transport
    index 
    @truck = Transport.find(@gps_nav_transport.transport_id)
    @gps_nav_transports = @truck.gps_nav_transports.order("created_at desc")

    respond_to do |format|
      format.js do 
        flash[:notice] = 'GPS отвязан'
        render :index
      end
    end
    
  end
  
  
  def new
    @truck = Transport.find(params[:truck])
    @gps_nav_transport = GpsNavTransport.new
    @gps_nav_transport.transport_id = @truck.id
    @gps = GpsNav.free_gps
  end

  def edit
    @gps_nav_transport = GpsNavTransport.find(params[:id])
    @truck = @gps_nav_transport.transport
    @gps = GpsNav.free_gps
    render :new
  end

  def create
    @gps_nav_transport = GpsNavTransport.new(gps_nav_transport_params)
    index
    @truck = @gps_nav_transport.transport
    @gps_nav_transports = @truck.gps_nav_transports.order("created_at desc")
    if @gps_nav_transport.save
      flash[:notice] = 'Связка сохранена' 
      render :index
    else
      @gps = GpsNav.free_gps
      render :new 
    end
  end  


  def update
    index
    @truck = @gps_nav_transport.transport
    @gps_nav_transports = @truck.gps_nav_transports.order("created_at desc")
    if  @gps_nav_transport.update(gps_nav_transport_params)
      flash[:notice] = 'Связка сохранена' 
      render :index
    else
      @gps = GpsNav.free_gps
      render :new 
    end
  end

  def destroy
    @gps_nav_transport.close
    respond_with(@gps_nav_transport)
  end

  private
    def set_gps_nav_transport
      @gps_nav_transport = GpsNavTransport.find(params[:id])
    end

    def gps_nav_transport_params
      params[:gps_nav_transport][:user_id] = current_user.id
      params.require(:gps_nav_transport).permit(:transport_id, :gps_nav_id, :start_date, :end_date, :user_id, :is_close)
    end
end

app/views/gps_nav_transports/_form.html.haml
= form_for @gps_nav_transport, html: { class: "form-horizontal", role: "form" }, remote: true do |f|
  -if  @gps_nav_transport.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "Ошибок: #{@gps_nav_transport.errors.count} "
      %ul
        - @gps_nav_transport.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :id unless @gps_nav_transport.new_record?
  = f.hidden_field :transport_id
  .alert.alert-info
    %strong Тягач
    = @truck.reg_num
  .well.well-sm
    .form-group
      .col-sm-4.control-label= f.label :gps_nav_id, "GPS-навигатор"
      .col-sm-8
        - if @gps_nav_transport.new_record?
          = f.collection_select( :gps_nav_id, @gps, :id, :name, |
            { prompt: @gps_nav_transport.gps_nav_id ? nil : "Выберите GPS-навигатор", |
            selected: @gps_nav_transport.gps_nav_id ? @gps_nav_transport.gps_nav_id : nil}, :class => 'form-control' ) 
        - else
          .alert.alert-info= @gps_nav_transport.gps_nav.name
    .form-group
      .col-sm-4.control-label= f.label :start_date, "С"
      .col-sm-7= f.text_field :start_date, size: 10
    .form-group
      .col-sm-4.control-label= f.label :end_date, "По"
      .col-sm-8= f.text_field :end_date, size: 10
    .form-group
      .col-sm-offset-4.col-sm-8
        = f.submit 'Сохранить', :class => 'btn btn-primary btn-sm'


:coffeescript
  $('#gps_nav_transport_start_date').datetimepicker timepicker: true
  $('#gps_nav_transport_end_date').datetimepicker timepicker: true

app/views/gps_nav_transports/_gps_transport_buttons.html.haml
= link_to 'Все', gps_nav_transports_path(vis: 'all' ), class: "btn btn-default btn-sm #{'btn-success' if user_session[:gps_nav_transports].blank? or user_session[:gps_nav_transports] == 'all'}", remote: true 

= link_to 'Тягачи без GPS', gps_nav_transports_path(vis: 'without_gps'), class: "btn btn-default btn-sm #{'btn-success' if user_session[:gps_nav_transports] == 'without_gps'}", remote: true 

app/views/gps_nav_transports/_gps_transports.html.haml
.table-responsive
  %table#gps_nav_transports
    %thead
      %tr
        %th Тягач
        %th GPS-навигатор
        %th C
        %th По
        %th Редактировал
    %tbody
      - @trucks.each do |truck|
        %tr{:id=> "#{truck.id}", :class => "#{'select_green' if @truck and @truck.id == truck.id}"}
          %td= link_to truck.reg_num, show_gps_nav_gps_nav_transport_path(truck), remote: true, class: "btn btn-default btn-xs"
          %td= truck.gps_nav_name
          %td= truck.gps_start_date
          %td= truck.gps_end_date
          %td= truck.editor_name

app/views/gps_nav_transports/_show_gps_nav.html.haml
- if @truck
  - unless @truck.chained_gps_nav_transports.any?
    = link_to new_gps_nav_transport_path(truck: @truck.id), class: 'btn btn-primary btn-xs', remote: true do
      %span.glyphicon.glyphicon-plus 
        Привязать GPS-навигатор к тягачу
  - if @gps_nav_transports.any?
    %table
      %thead
        %tr
          %th Тягач
          %th GPS-навигатор
          %th C
          %th По
          %th Редактировал
          %th 
          %th 
      %tbody
        - @gps_nav_transports.each do |gps_nav_transport|
          %tr{:class => "#{'select_green' if gps_nav_transport.chained?}"}
            %td= gps_nav_transport.transport.reg_num if gps_nav_transport.transport
            %td= gps_nav_transport.gps_nav.name if gps_nav_transport.gps_nav
            %td= gps_nav_transport.start_date
            %td= gps_nav_transport.end_date
            %td= gps_nav_transport.user.fullname if gps_nav_transport.user
            %td.edit{:title => "Редатировать"}= link_to image_tag("edit.png"), edit_gps_nav_transport_path(gps_nav_transport), remote: true if gps_nav_transport.chained?
            %td.del{:title => "Расцепить"}
              - if gps_nav_transport.chained?
                = link_to unchain_gps_nav_gps_nav_transport_path(gps_nav_transport), data: { confirm: 'Точно расцепить?' }, remote: true do
                  %span.glyphicon.glyphicon-random 

app/views/gps_nav_transports/edit.html.haml
.page-header

  %h2 Редактирование связки GPS-навигатор : тягач

= render 'form'

app/views/gps_nav_transports/index.html.haml
.row
  .col-md-8
    .panel.panel-default
      .panel-heading 
        %h2 Связки GPS-навигатор : тягач
      #index.panel-body= render 'gps_transports'

  #gps_nav_controls.col-md-4
    .well.well-sm.btn-toolbar#gps_nav_buttons
      = render 'gps_transport_buttons'

    .panel.panel-default
      .panel-heading Связка тягач-GPS
      #show_gps_nav.panel-body
        = render 'show_gps_nav'

app/views/gps_nav_transports/index.js.haml
notice('#{flash[:notice]}');
$("#show_gps_nav").html("#{j render 'show_gps_nav' }");

$("#gps_nav_buttons").html("#{j render 'gps_transport_buttons' }");
$("#index").html("#{j render 'gps_transports' }");
$(document).ready(function() {$("#gps_nav_transports").dataTable({lengthMenu: [[30, 60, 100, -1], [30, 60, 100, "Все"]], columnDefs: [{type: 'date-euro', targets: [2, 3]}] });});
$('#popup').hide();
$('#popup_content').html('');

app/views/gps_nav_transports/new.js.haml
$("#popup_content").html("#{j render 'form' }");
$("#popup_head span").html("Cвязка GPS - Тягач: #{j @truck.reg_num }");
$("#popup").show();

app/views/gps_nav_transports/show_gps_nav.js.haml
$("#show_gps_nav").html("#{j render 'show_gps_nav' }");

$("#gps_nav_buttons").html("#{j render 'gps_transport_buttons' }");
$('#popup').hide();
$('#popup_content').html('');
$("#gps_nav_transports .select_green").removeClass('select_green')
$("##{@truck.id}").addClass('select_green')